(()=>{
'use strict';
const NS='http://www.w3.org/2000/svg', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clone=o=>JSON.parse(JSON.stringify(o));
const equipmentData=[
 {equipmentId:'1A01A',type:'Transformer',phase:1,pod:'POD/ROMP 1',progress:{percent:100}},{equipmentId:'1A02A',type:'ATS',phase:1,pod:'POD/ROMP 1',progress:{percent:75}},{equipmentId:'1A03A',type:'Switchgear',phase:1,pod:'POD/ROMP 1',progress:{percent:50}},{equipmentId:'1A04A',type:'Panelboard',phase:1,pod:'POD/ROMP 1',progress:{percent:100}},
 {equipmentId:'2A01A',type:'Switchgear',phase:2,pod:'POD/ROMP 2',progress:{percent:25}},{equipmentId:'2A02A',type:'Panelboard',phase:2,pod:'POD/ROMP 2',progress:{percent:75}},{equipmentId:'2A03A',type:'PDU',phase:2,pod:'POD/ROMP 2',progress:{percent:50}},{equipmentId:'2A04A',type:'UPS',phase:2,pod:'POD/ROMP 2',progress:{percent:100}},{equipmentId:'2A05A',type:'Meter',phase:2,pod:'POD/ROMP 2',progress:{percent:100}},{equipmentId:'2A06A',type:'Load Bank',phase:2,pod:'POD/ROMP 2',progress:{percent:0}},
 {equipmentId:'3B01A',type:'ATS',phase:3,pod:'POD/ROMP 3',progress:{percent:75}},{equipmentId:'3B02A',type:'Switchgear',phase:3,pod:'POD/ROMP 3',progress:{percent:50}},{equipmentId:'3B03A',type:'Panelboard',phase:3,pod:'POD/ROMP 3',progress:{percent:75}},{equipmentId:'3B04A',type:'Generator',phase:3,pod:'POD/ROMP 3',progress:{percent:100}},{equipmentId:'3B05A',type:'PDU',phase:3,pod:'POD/ROMP 3',progress:{percent:100}},{equipmentId:'3B06A',type:'UPS',phase:3,pod:'POD/ROMP 3',progress:{percent:50}},{equipmentId:'3B07A',type:'Busway',phase:3,pod:'POD/ROMP 3',progress:{}},{equipmentId:'3B08A',type:'Disconnect',phase:3,pod:'POD/ROMP 3',progress:{percent:0}}
];
const node=(id,x,y)=>({id,x,y,w:180,h:100,shape:'auto',locked:false}), zone=(id,text,x,y,w,h)=>({id,text,x,y,w,h,locked:false}), con=(from,to,arrow=false)=>({id:'c-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),from,to,arrow,bends:[]});
const defaults={
 overall:{nodes:[node('1A01A',250,180),node('1A02A',610,180),node('1A03A',900,180),node('1A04A',900,360),node('2A01A',300,660),node('2A02A',220,870),node('2A03A',470,870),node('2A04A',720,870),node('2A05A',220,1060),node('2A06A',470,1060),node('3B01A',1040,660),node('3B02A',900,870),node('3B03A',1160,870),node('3B04A',1450,870),node('3B05A',900,1060),node('3B06A',1160,1060)],zones:[zone('z1','PHASE 1',540,90,570,430),zone('z2','PHASE 2',150,560,680,650),zone('z3','PHASE 3',850,560,780,650)],labels:[{id:'utility',text:'UTILITY SERVICE',x:40,y:230,locked:false}],connections:[],collapsed:false},
 'phase-1':{nodes:[node('1A01A',250,260),node('1A02A',600,260),node('1A03A',920,260),node('1A04A',920,500)],zones:[],labels:[],connections:[],collapsed:false},
 'phase-2':{nodes:[node('2A01A',520,220),node('2A02A',230,500),node('2A03A',500,500),node('2A04A',770,500),node('2A05A',230,760),node('2A06A',500,760)],zones:[],labels:[],connections:[],collapsed:false},
 'phase-3':{nodes:[node('3B01A',590,220),node('3B02A',300,500),node('3B03A',590,500),node('3B04A',900,500),node('3B05A',300,760),node('3B06A',590,760)],zones:[],labels:[],connections:[],collapsed:false}
};
function seedConnections(){
 defaults.overall.connections=[con('1A01A','1A02A'),con('1A02A','1A03A'),con('1A03A','1A04A'),con('1A01A','2A01A'),con('1A01A','3B01A'),con('2A01A','2A02A'),con('2A01A','2A03A'),con('2A01A','2A04A'),con('2A02A','2A05A'),con('2A03A','2A06A'),con('3B01A','3B02A'),con('3B01A','3B03A'),con('3B03A','3B04A',true),con('3B02A','3B05A'),con('3B03A','3B06A')];
 defaults['phase-1'].connections=[con('1A01A','1A02A'),con('1A02A','1A03A'),con('1A03A','1A04A')];
 defaults['phase-2'].connections=[con('2A01A','2A02A'),con('2A01A','2A03A'),con('2A01A','2A04A'),con('2A02A','2A05A'),con('2A03A','2A06A')];
 defaults['phase-3'].connections=[con('3B01A','3B02A'),con('3B01A','3B03A'),con('3B03A','3B04A',true),con('3B02A','3B05A'),con('3B03A','3B06A')];
} seedConnections();
const E={svg:$('#diagramSvg'),world:$('#worldLayer'),grid:$('#gridRect'),zones:$('#zonesLayer'),connections:$('#connectionsLayer'),nodes:$('#nodesLayer'),labels:$('#labelsLayer'),overlay:$('#overlayLayer'),viewport:$('#viewport'),pool:$('#poolPanel'),poolList:$('#poolList'),poolCount:$('#poolCount'),poolSearch:$('#poolSearch'),diagram:$('#diagramSelect'),view:$('#viewSelect'),subtitle:$('#diagramSubtitle'),saveState:$('#saveState'),autosave:$('#autosaveStatus'),selected:$('#selectedStatus'),stats:$('#statsStatus'),zoom:$('#zoomLabel'),mini:$('#miniMap'),form:$('#propertyForm'),empty:$('#emptyProperties'),name:$('#propName'),shape:$('#propShape'),width:$('#propWidth'),height:$('#propHeight'),arrow:$('#propArrow'),locked:$('#propLocked'),open:$('#openEquipmentBtn'),remove:$('#removeBtn'),readout:$('#equipmentReadout'),toast:$('#toast'),workspace:$('#workspace')};
let diagramId='overall',state,tool='select',poolTab='all',selection=[],history=[],future=[],transform={x:0,y:0,scale:1},drag=null,pan=null,connectStart=null,gridOn=true,saveTimer=null,poolHidden=false;
const eq=id=>equipmentData.find(e=>e.equipmentId===id), pct=e=>{for(const k of ['percent','percentage','completionPercent','completePercent','percentComplete']){const v=parseFloat(String(e?.progress?.[k]??'').replace('%',''));if(Number.isFinite(v))return Math.max(0,Math.min(100,Math.round(v)))}return e?.complete===true?100:e?.complete===false?0:null}, color=e=>{const p=pct(e);return p===null?'#999':p===100?'#98cb70':p>=51?'#f2bd3f':p>=1?'#d67ab6':'#de3b34'};
const visibleEquipment=()=>E.view.value==='all'?equipmentData:equipmentData.filter(e=>e.phase===Number(E.view.value.split('-')[1]));
const shapeFor=(e,n)=>{if(n.shape&&n.shape!=='auto')return n.shape;const t=(e?.type||'').toLowerCase();for(const [key,val] of [['ats','ats'],['transform','transformer'],['generator','generator'],['switchgear','switchgear'],['panel','panelboard'],['ups','ups'],['pdu','pdu'],['meter','meter'],['busway','busway'],['disconnect','disconnect']])if(t.includes(key))return val;return'rectangle'};
const svg=(tag,a={})=>{const el=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>el.setAttribute(k,v));return el};
function load(id){diagramId=id;state=NexusOneLineStorage.load(id)||clone(defaults[id]);state.connections.forEach(c=>c.bends??=[]);selection=[];history=[];future=[];transform={x:0,y:0,scale:1};E.view.value=id==='overall'?'all':id;E.subtitle.textContent=id==='overall'?'Building A • Overall':'Building A • '+id.replace('-',' ').replace(/\b\w/g,m=>m.toUpperCase());render();requestAnimationFrame(fit)}
function checkpoint(){history.push(clone(state));if(history.length>80)history.shift();future=[]}
function undo(){if(!history.length)return;future.push(clone(state));state=history.pop();selection=[];render();queueSave()}
function redo(){if(!future.length)return;history.push(clone(state));state=future.pop();selection=[];render();queueSave()}
function queueSave(){E.saveState.textContent='Unsaved';E.saveState.style.color='#f2bd3f';E.autosave.textContent='Auto-save: Unsaved';clearTimeout(saveTimer);saveTimer=setTimeout(save,650)}
function save(){try{NexusOneLineStorage.save(diagramId,state);E.saveState.textContent='Saved';E.saveState.style.color='#69d96f';E.autosave.textContent='Auto-save: Saved'}catch(err){E.saveState.textContent='Save Failed';E.saveState.style.color='#ff5555';E.autosave.textContent='Auto-save: Failed'}}
function render(){renderZones();renderConnections();renderNodes();renderLabels();renderOverlay();renderPool();renderProperties();applyTransform();updateStatus();renderMini();$('#collapseBtn').textContent=state.collapsed?'Expand Phases':'Collapse Phases'}
function renderPool(){const placed=new Set(state.nodes.map(n=>n.id)),search=E.poolSearch.value.toLowerCase().trim();let list=visibleEquipment().filter(e=>{const p=placed.has(e.equipmentId);return(poolTab==='all'||poolTab==='placed'&&p||poolTab==='unplaced'&&!p)&&(e.equipmentId+' '+e.type+' '+e.pod).toLowerCase().includes(search)});E.poolCount.textContent=list.length;E.poolList.innerHTML='';if(!list.length)E.poolList.innerHTML='<div class="pool-empty">No equipment in this view.</div>';list.forEach(e=>{const p=placed.has(e.equipmentId),item=document.createElement('div');item.className='pool-item'+(p?' placed':'');item.draggable=!p;item.innerHTML=`<span class="pool-accent" style="background:${color(e)}"></span><div><div class="pool-name">${e.equipmentId}</div><div class="pool-type">${e.type} • Phase ${e.phase}${p?' • Placed':''}</div></div><span class="pool-pct" style="color:${color(e)}">${pct(e)===null?'—':pct(e)+'%'}</span>`;item.ondragstart=ev=>ev.dataTransfer.setData('text/equipment-id',e.equipmentId);item.onclick=()=>{if(p){selection=[{kind:'node',id:e.equipmentId}];render()}};E.poolList.appendChild(item)});E.workspace.classList.toggle('pool-hidden',poolHidden)}
function renderZones(){E.zones.innerHTML='';if(state.collapsed&&diagramId==='overall')return;state.zones.forEach(z=>{const g=svg('g',{class:'zone'+(isSelected('zone',z.id)?' selected':'')+(z.locked?' locked':''),transform:`translate(${z.x} ${z.y})`});g.append(svg('rect',{width:z.w,height:z.h,rx:10}));const t=svg('text',{x:16,y:28,fill:phaseColor(z.text)});t.textContent=z.text;g.append(t);g.onpointerdown=e=>startDrag(e,'zone',z.id);g.onclick=e=>{e.stopPropagation();select('zone',z.id,e)};E.zones.append(g)})}
function phaseColor(text){return String(text).includes('1')?'#5f7e21':String(text).includes('2')?'#754aa5':String(text).includes('3')?'#c86416':'#444'}
function renderNodes(){E.nodes.innerHTML='';if(state.collapsed&&diagramId==='overall'){renderPhaseSummaries();return}const allowed=new Set(visibleEquipment().map(e=>e.equipmentId));state.nodes.filter(n=>allowed.has(n.id)).forEach(n=>{const e=eq(n.id),g=svg('g',{class:'node'+(isSelected('node',n.id)?' selected':'')+(n.locked?' locked':''),transform:`translate(${n.x} ${n.y})`});drawNode(g,n,e);drawPorts(g,n);g.onpointerdown=ev=>startDrag(ev,'node',n.id);g.onclick=ev=>{ev.stopPropagation();if(tool==='connect')connectClick(n.id);else select('node',n.id,ev)};g.ondblclick=()=>window.open(`equipment.html?eq=${encodeURIComponent(n.id)}`,'_blank');E.nodes.append(g)})}
function drawNode(g,n,e){const w=n.w,h=n.h,s=shapeFor(e,n),fill=color(e);let body;if(s==='ats')body=svg('polygon',{class:'body',points:`20,0 ${w-20},0 ${w},${h/2} ${w-20},${h} 20,${h} 0,${h/2}`,fill});else if(['generator','meter'].includes(s))body=svg('ellipse',{class:'body',cx:w/2,cy:h/2,rx:w/2,ry:h/2,fill});else if(s==='transformer')body=svg('polygon',{class:'body',points:`${w*.12},0 ${w*.88},0 ${w},${h/2} ${w*.88},${h} ${w*.12},${h} 0,${h/2}`,fill});else body=svg('rect',{class:'body',width:w,height:h,rx:s==='ups'?14:4,fill});g.append(body);drawSymbol(g,s,w,h);const t1=svg('text',{class:'id',x:w/2,y:h*.36,'text-anchor':'middle'});t1.textContent=e?.equipmentId||n.id;const t2=svg('text',{class:'type',x:w/2,y:h*.58,'text-anchor':'middle'});t2.textContent=(e?.type||'Equipment').toUpperCase();const t3=svg('text',{class:'pct',x:w/2,y:h*.8,'text-anchor':'middle'});t3.textContent=pct(e)===null?'NO DATA':pct(e)+'%';g.append(t1,t2,t3);if(n.locked){const l=svg('text',{x:w-12,y:16,'text-anchor':'end','font-size':14});l.textContent='🔒';g.append(l)}}
function drawSymbol(g,s,w,h){const p=svg('path',{class:'symbol',d:s==='ats'?`M18 ${h/2}h18m-9 0 15-12m-15 12 15 12 M${w-18} ${h/2}h-18m9 0-15-12m15 12-15 12`:s==='transformer'?`M28 18q18 12 0 24q18 12 0 24 M48 18q18 12 0 24q18 12 0 24`:s==='generator'?`M18 ${h/2}h12 M${w-30} ${h/2}h12`:s==='meter'?`M${w/2-18} ${h/2}a18 18 0 1 0 36 0a18 18 0 1 0-36 0 M${w/2} ${h/2}l12-10`:s==='disconnect'?`M20 ${h/2}h28 M48 ${h/2}l28-20 M76 ${h/2}h28`:s==='busway'?`M18 ${h/2}H${w-18}`:`M20 20v${h-40}`});g.append(p)}
function drawPorts(g,n){[['top',n.w/2,0],['right',n.w,n.h/2],['bottom',n.w/2,n.h],['left',0,n.h/2]].forEach(([name,x,y])=>{const p=svg('circle',{class:'port',cx:x,cy:y,r:5,'data-port':name});p.onpointerdown=ev=>{ev.stopPropagation();setTool('connect');connectStart=n.id;toast('Select the equipment to connect.')} ;g.append(p)})}
function renderConnections(){E.connections.innerHTML='';state.connections.forEach(c=>{const a=state.nodes.find(n=>n.id===c.from),b=state.nodes.find(n=>n.id===c.to);if(!a||!b)return;const pts=route(a,b,c.bends||[]),path=svg('path',{class:'connection'+(isSelected('connection',c.id)?' selected':''),d:pathD(pts)});if(c.arrow)path.setAttribute('marker-end','url(#arrow)');path.onclick=ev=>{ev.stopPropagation();select('connection',c.id,ev)};path.ondblclick=ev=>{ev.stopPropagation();checkpoint();const p=worldPoint(ev.clientX,ev.clientY);c.bends.push({x:snap(p.x),y:snap(p.y)});queueSave();render()};E.connections.append(path);pts.slice(1,-1).forEach(p=>E.connections.append(svg('circle',{class:'junction',cx:p.x,cy:p.y,r:4})))})}
function route(a,b,bends){const ac={x:a.x+a.w/2,y:a.y+a.h/2},bc={x:b.x+b.w/2,y:b.y+b.h/2};if(bends.length)return [ac,...bends,bc];const dx=Math.abs(bc.x-ac.x),dy=Math.abs(bc.y-ac.y);return dx>=dy?[ac,{x:(ac.x+bc.x)/2,y:ac.y},{x:(ac.x+bc.x)/2,y:bc.y},bc]:[ac,{x:ac.x,y:(ac.y+bc.y)/2},{x:bc.x,y:(ac.y+bc.y)/2},bc]}
const pathD=p=>p.map((v,i)=>(i?'L':'M')+v.x+' '+v.y).join(' ');
function renderLabels(){E.labels.innerHTML='';if(state.collapsed&&diagramId==='overall')return;state.labels.forEach(l=>{const g=svg('g',{class:'label-item'+(isSelected('label',l.id)?' selected':'')+(l.locked?' locked':''),transform:`translate(${l.x} ${l.y})`});const t=svg('text');t.textContent=l.text;g.append(t);g.onpointerdown=e=>startDrag(e,'label',l.id);g.onclick=e=>{e.stopPropagation();select('label',l.id,e)};E.labels.append(g)})}
function renderOverlay(){E.overlay.innerHTML='';if(selection.length!==1)return;const s=selection[0],o=getObj(s);if(!o)return;if((s.kind==='node'||s.kind==='zone')&&!o.locked){const h=svg('rect',{class:'resize-handle',x:o.x+o.w-7,y:o.y+o.h-7,width:14,height:14});h.onpointerdown=e=>startResize(e,s.kind,s.id);E.overlay.append(h)}if(s.kind==='connection'){(o.bends||[]).forEach((b,i)=>{const h=svg('circle',{class:'bend-handle',cx:b.x,cy:b.y,r:7});h.onpointerdown=e=>startBend(e,o.id,i);E.overlay.append(h)})}}
function renderPhaseSummaries(){[1,2,3].forEach((p,i)=>{const list=equipmentData.filter(e=>e.phase===p),avg=Math.round(list.reduce((a,e)=>a+(pct(e)||0),0)/list.length),x=240+i*410,y=360,g=svg('g',{class:'phase-summary',transform:`translate(${x} ${y})`});g.append(svg('rect',{width:330,height:150,rx:14,fill:avg===100?'#98cb70':avg>=51?'#f2bd3f':'#d67ab6'}));[['PHASE '+p,75,42,24], [list.length+' EQUIPMENT',75,82,16],[avg+'% COMPLETE',75,116,18]].forEach(([text,x1,y1,size])=>{const t=svg('text',{x:x1,y:y1,'font-size':size});t.textContent=text;g.append(t)});g.onclick=()=>{E.diagram.value='phase-'+p;load('phase-'+p)};E.nodes.append(g)})}
function renderProperties(){const s=selection.length===1?selection[0]:null;E.empty.classList.toggle('hidden',!!s);E.form.classList.toggle('hidden',!s);if(!s)return;const o=getObj(s);if(!o)return;$('#shapeRow').classList.toggle('hidden',s.kind!=='node');$('#sizeRow').classList.toggle('hidden',!['node','zone'].includes(s.kind));$('#arrowRow').classList.toggle('hidden',s.kind!=='connection');$('#lockRow').classList.toggle('hidden',!['node','zone','label'].includes(s.kind));E.open.classList.toggle('hidden',s.kind!=='node');E.name.disabled=s.kind==='node'||s.kind==='connection';E.name.value=s.kind==='node'?o.id:s.kind==='connection'?o.from+' → '+o.to:o.text;E.shape.value=o.shape||'auto';E.width.value=o.w||'';E.height.value=o.h||'';E.arrow.checked=!!o.arrow;E.locked.checked=!!o.locked;E.remove.textContent=s.kind==='node'?'Return to Equipment Pool':'Delete '+s.kind;E.readout.innerHTML=s.kind==='node'?`<b>${eq(o.id)?.type||'Equipment'}</b><br>Phase ${eq(o.id)?.phase||'—'} • ${eq(o.id)?.pod||'—'}<br>Completion: ${pct(eq(o.id))===null?'No data':pct(eq(o.id))+'%'}<br>Position: ${Math.round(o.x)}, ${Math.round(o.y)}`:''}
function select(kind,id,ev){const item={kind,id};if(ev&&(ev.ctrlKey||ev.metaKey)){const idx=selection.findIndex(s=>s.kind===kind&&s.id===id);idx>=0?selection.splice(idx,1):selection.push(item)}else selection=[item];render()}
const isSelected=(kind,id)=>selection.some(s=>s.kind===kind&&s.id===id), getObj=s=>state[{node:'nodes',zone:'zones',label:'labels',connection:'connections'}[s.kind]].find(o=>o.id===s.id);
function startDrag(ev,kind,id){if(tool!=='select'||ev.button!==0)return;const primary=getObj({kind,id});if(primary.locked)return;ev.stopPropagation();if(!isSelected(kind,id))selection=[{kind,id}];checkpoint();const p=worldPoint(ev.clientX,ev.clientY),items=selection.filter(s=>['node','zone','label'].includes(s.kind)).map(s=>({s,o:getObj(s),x:getObj(s).x,y:getObj(s).y})).filter(v=>!v.o.locked);drag={mode:'move',start:p,items};window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function startResize(ev,kind,id){ev.stopPropagation();checkpoint();const o=getObj({kind,id}),p=worldPoint(ev.clientX,ev.clientY);drag={mode:'resize',o,start:p,w:o.w,h:o.h};window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function startBend(ev,id,index){ev.stopPropagation();checkpoint();drag={mode:'bend',o:getObj({kind:'connection',id}),index};window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function moveDrag(ev){if(!drag)return;const p=worldPoint(ev.clientX,ev.clientY);if(drag.mode==='move')drag.items.forEach(v=>{v.o.x=snap(v.x+p.x-drag.start.x);v.o.y=snap(v.y+p.y-drag.start.y)});else if(drag.mode==='resize'){drag.o.w=Math.max(70,snap(drag.w+p.x-drag.start.x));drag.o.h=Math.max(45,snap(drag.h+p.y-drag.start.y))}else{drag.o.bends[drag.index]={x:snap(p.x),y:snap(p.y)}}renderZones();renderConnections();renderNodes();renderLabels();renderOverlay();updateStatus();renderMini()}
function endDrag(){drag=null;window.removeEventListener('pointermove',moveDrag);queueSave();render()}
function connectClick(id){if(!connectStart){connectStart=id;selection=[{kind:'node',id}];toast('Select the second equipment item.');render();return}if(connectStart===id)return;const duplicate=state.connections.some(c=>(c.from===connectStart&&c.to===id)||(c.from===id&&c.to===connectStart));if(duplicate){toast('Those equipment items are already connected.');connectStart=null;setTool('select');return}checkpoint();state.connections.push(con(connectStart,id));connectStart=null;selection=[{kind:'node',id}];queueSave();setTool('select');render()}
function removeSelected(){if(!selection.length)return;checkpoint();for(const s of [...selection]){const o=getObj(s);if(!o)continue;if(s.kind==='node'){const related=state.connections.filter(c=>c.from===o.id||c.to===o.id);if(related.length&&!confirm(`Returning ${o.id} to the pool will remove ${related.length} connection(s). Continue?`)){history.pop();return}state.nodes=state.nodes.filter(n=>n.id!==o.id);state.connections=state.connections.filter(c=>c.from!==o.id&&c.to!==o.id)}else state[{zone:'zones',label:'labels',connection:'connections'}[s.kind]]=state[{zone:'zones',label:'labels',connection:'connections'}[s.kind]].filter(x=>x.id!==o.id)}selection=[];queueSave();render()}
function updateProps(){if(selection.length!==1)return;checkpoint();const s=selection[0],o=getObj(s);if(s.kind==='node'){o.shape=E.shape.value;o.w=+E.width.value||o.w;o.h=+E.height.value||o.h;o.locked=E.locked.checked}else if(s.kind==='zone'){o.text=E.name.value;o.w=+E.width.value||o.w;o.h=+E.height.value||o.h;o.locked=E.locked.checked}else if(s.kind==='label'){o.text=E.name.value;o.locked=E.locked.checked}else o.arrow=E.arrow.checked;queueSave();render()}
function addLabel(){checkpoint();const p=centerWorld(),id='label-'+Date.now();state.labels.push({id,text:'NEW LABEL',x:snap(p.x),y:snap(p.y),locked:false});selection=[{kind:'label',id}];queueSave();render()}
function addZone(){checkpoint();const p=centerWorld(),id='zone-'+Date.now();state.zones.push(zone(id,'NEW ZONE',snap(p.x-250),snap(p.y-150),500,300));selection=[{kind:'zone',id}];queueSave();render()}
function autoArrange(){checkpoint();const nodes=state.nodes.filter(n=>visibleEquipment().some(e=>e.equipmentId===n.id));const groups={};nodes.forEach(n=>(groups[eq(n.id)?.phase||0]??=[]).push(n));let gy=180;Object.keys(groups).sort().forEach(ph=>{groups[ph].forEach((n,i)=>{n.x=240+(i%5)*240;n.y=gy+Math.floor(i/5)*170});gy+=Math.ceil(groups[ph].length/5)*170+220});queueSave();render();fit();toast('Equipment arranged. Undo is available.')}
function align(axis){const items=selection.filter(s=>['node','zone','label'].includes(s.kind)).map(getObj);if(items.length<2)return toast('Select two or more items with Ctrl-click.');checkpoint();const v=Math.min(...items.map(o=>o[axis]));items.forEach(o=>o[axis]=v);queueSave();render()}
function distribute(axis){const items=selection.filter(s=>['node','zone','label'].includes(s.kind)).map(getObj).sort((a,b)=>a[axis]-b[axis]);if(items.length<3)return toast('Select three or more items with Ctrl-click.');checkpoint();const gap=(items.at(-1)[axis]-items[0][axis])/(items.length-1);items.forEach((o,i)=>o[axis]=snap(items[0][axis]+gap*i));queueSave();render()}
function toggleLock(){const items=selection.filter(s=>['node','zone','label'].includes(s.kind)).map(getObj);if(!items.length)return toast('Select an item first.');checkpoint();const next=!items.every(o=>o.locked);items.forEach(o=>o.locked=next);queueSave();render();toast(next?'Selection locked.':'Selection unlocked.')}
function drop(ev){ev.preventDefault();const id=ev.dataTransfer.getData('text/equipment-id');if(!id||state.nodes.some(n=>n.id===id))return;checkpoint();const p=worldPoint(ev.clientX,ev.clientY);state.nodes.push(node(id,snap(p.x-90),snap(p.y-50)));selection=[{kind:'node',id}];queueSave();render()}
function worldPoint(cx,cy){const r=E.svg.getBoundingClientRect();return{x:(cx-r.left-transform.x)/transform.scale,y:(cy-r.top-transform.y)/transform.scale}}
function centerWorld(){const r=E.svg.getBoundingClientRect();return worldPoint(r.left+r.width/2,r.top+r.height/2)}
const snap=v=>gridOn?Math.round(v/20)*20:v;
function applyTransform(){E.world.setAttribute('transform',`translate(${transform.x} ${transform.y}) scale(${transform.scale})`);E.grid.setAttribute('transform',`translate(${transform.x} ${transform.y}) scale(${transform.scale})`);E.zoom.textContent=Math.round(transform.scale*100)+'%'}
function fit(){let items=state.collapsed&&diagramId==='overall'?[{x:240,y:360,w:1150,h:150}]:[...state.nodes,...state.zones,...state.labels.map(l=>({...l,w:180,h:40}))];if(!items.length){transform={x:20,y:20,scale:1};return applyTransform()}const minX=Math.min(...items.map(o=>o.x)),minY=Math.min(...items.map(o=>o.y)),maxX=Math.max(...items.map(o=>o.x+(o.w||180))),maxY=Math.max(...items.map(o=>o.y+(o.h||100))),r=E.svg.getBoundingClientRect(),pad=80,s=Math.min((r.width-pad*2)/(maxX-minX||1),(r.height-pad*2)/(maxY-minY||1),1.35);transform.scale=Math.max(.18,s);transform.x=(r.width-(maxX-minX)*s)/2-minX*s;transform.y=(r.height-(maxY-minY)*s)/2-minY*s;applyTransform()}
function zoom(dir,cx,cy){const r=E.svg.getBoundingClientRect(),x=(cx??r.left+r.width/2)-r.left,y=(cy??r.top+r.height/2)-r.top,old=transform.scale,next=Math.max(.18,Math.min(2.8,old*(dir>0?1.12:.89)));transform.x=x-(x-transform.x)*(next/old);transform.y=y-(y-transform.y)*(next/old);transform.scale=next;applyTransform()}
function updateStatus(){E.stats.textContent=`${state.nodes.filter(n=>visibleEquipment().some(e=>e.equipmentId===n.id)).length} equipment • ${state.connections.length} connections`;E.selected.textContent=selection.length?`Selected: ${selection.length} item${selection.length===1?'':'s'}`:'Selected: none'}
function renderMini(){E.mini.innerHTML='';E.mini.append(svg('rect',{x:0,y:0,width:320,height:170,fill:'#101012'}));if(!state.nodes.length)return;const minX=Math.min(...state.nodes.map(n=>n.x)),minY=Math.min(...state.nodes.map(n=>n.y)),maxX=Math.max(...state.nodes.map(n=>n.x+n.w)),maxY=Math.max(...state.nodes.map(n=>n.y+n.h)),s=Math.min(290/(maxX-minX||1),140/(maxY-minY||1));state.nodes.forEach(n=>E.mini.append(svg('rect',{x:15+(n.x-minX)*s,y:15+(n.y-minY)*s,width:Math.max(5,n.w*s),height:Math.max(4,n.h*s),fill:color(eq(n.id)),stroke:'#fff','stroke-width':.5}))) }
function setTool(name){tool=name;connectStart=null;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===name));E.viewport.classList.toggle('connect-mode',name==='connect')}
function toast(text){E.toast.textContent=text;E.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.add('hidden'),2200)}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$$('.pool-tab').forEach(b=>b.onclick=()=>{poolTab=b.dataset.poolTab;$$('.pool-tab').forEach(x=>x.classList.toggle('active',x===b));renderPool()});
E.poolSearch.oninput=renderPool;E.diagram.onchange=()=>load(E.diagram.value);E.view.onchange=()=>{selection=[];render();fit()};$('#saveBtn').onclick=()=>{save();toast('Diagram saved locally.')};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#fitBtn').onclick=fit;$('#zoomInBtn').onclick=()=>zoom(1);$('#zoomOutBtn').onclick=()=>zoom(-1);$('#addLabelBtn').onclick=addLabel;$('#addZoneBtn').onclick=addZone;$('#autoArrangeBtn').onclick=autoArrange;$('#alignLeftBtn').onclick=()=>align('x');$('#alignTopBtn').onclick=()=>align('y');$('#distributeHBtn').onclick=()=>distribute('x');$('#distributeVBtn').onclick=()=>distribute('y');$('#lockBtn').onclick=toggleLock;$('#collapseBtn').onclick=()=>{if(diagramId!=='overall')return toast('Phase collapsing is available on the overall diagram.');checkpoint();state.collapsed=!state.collapsed;queueSave();render();fit()};$('#gridBtn').onclick=e=>{gridOn=!gridOn;E.grid.style.display=gridOn?'':'none';e.currentTarget.textContent='Grid: '+(gridOn?'On':'Off');$('#snapStatus').textContent=`Grid: ${gridOn?'On':'Off'} • Snap: ${gridOn?'On':'Off'}`};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():E.workspace.requestFullscreen();$('#hidePoolBtn').onclick=()=>{poolHidden=true;renderPool();fit()};$('#showPoolBtn').onclick=()=>{poolHidden=false;renderPool();fit()};
E.open.onclick=()=>selection.length===1&&selection[0].kind==='node'&&window.open(`equipment.html?eq=${encodeURIComponent(selection[0].id)}`,'_blank');E.remove.onclick=removeSelected;[E.name,E.shape,E.width,E.height,E.arrow,E.locked].forEach(x=>x.onchange=updateProps);
E.viewport.ondragover=e=>e.preventDefault();E.viewport.ondrop=drop;E.viewport.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1:-1,e.clientX,e.clientY)};E.svg.onclick=e=>{if(e.target===E.svg||e.target===E.grid){selection=[];connectStart=null;render()}};
E.viewport.onpointerdown=e=>{if(e.button===1||e.button===2||e.shiftKey){pan={x:e.clientX,y:e.clientY,tx:transform.x,ty:transform.y};E.viewport.setPointerCapture?.(e.pointerId)}};E.viewport.onpointermove=e=>{if(pan){transform.x=pan.tx+e.clientX-pan.x;transform.y=pan.ty+e.clientY-pan.y;applyTransform()}};E.viewport.onpointerup=()=>pan=null;E.viewport.oncontextmenu=e=>e.preventDefault();
window.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'||e.key==='Backspace'&&!['INPUT','SELECT'].includes(document.activeElement.tagName))removeSelected();else if(e.key==='Escape'){selection=[];setTool('select');render()}};window.onresize=fit;load('overall');
})();
